// Generated by https://quicktype.io

export interface JSONRoot {
    photos: Photo[];
}

export interface Photo {
    id:       string;
    title:    string;
    caption:  string;
    source:   string;
    comments: Comment[];
}
export interface Comment {
    comment: string;
    author: string;
}
